# Generated by Django 5.0.7 on 2024-08-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0002_collaborator_data_contratacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='RG',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
