# Generated by Django 5.0.7 on 2024-08-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0003_collaborator_rg'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='ASO',
            field=models.ImageField(blank=True, null=True, upload_to='GestaoHR/imagens/ASO/'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='CNH',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='Controle_folha_ponto',
            field=models.ImageField(blank=True, null=True, upload_to='GestaoHR/imagens/Controle_folha_ponto/'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='PIS',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='Salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='Seguro_de_vida',
            field=models.ImageField(blank=True, null=True, upload_to='GestaoHR/imagens/Seguro_vida/'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='Servico',
            field=models.CharField(blank=True, choices=[('administrativo', 'administrativo'), ('Externo', 'Externo')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='Vencimento_CNH',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='matricula',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='validade_aso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
