# Generated by Django 5.0.7 on 2024-08-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0004_collaborator_aso_collaborator_cnh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='Data_ferias',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='Salario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='Servico',
            field=models.CharField(choices=[('Administrativo', 'Administrativo'), ('Externo', 'Externo')], default='Externo', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='validade_aso',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
