# Generated by Django 5.0.7 on 2024-08-09 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0006_alter_collaborator_aso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Arquivo_ponto', models.FileField(upload_to='GestaoHR/imagens/Controle_folha_ponto/')),
                ('data_upload', models.DateField(auto_now_add=True)),
                ('Nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_mensal', to='GestaoHR.collaborator')),
            ],
        ),
    ]
