# Generated by Django 5.0.7 on 2024-08-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0008_remove_aquivo_data_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquivo',
            name='Ano',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='aquivo',
            name='Mes',
            field=models.CharField(choices=[('Jan', 'Jan'), ('Fev', 'Fev'), ('Mar', 'Mar'), ('Abr', 'Abr'), ('Mai', 'Mai'), ('Jun', 'Jun'), ('Jul', 'Jul'), ('Ago', 'Ago'), ('Set', 'Set'), ('Out', 'Out'), ('Nov', 'Nov'), ('Dez', 'Dez')], default='Jan', max_length=6),
            preserve_default=False,
        ),
    ]
