# Generated by Django 5.0.7 on 2024-08-10 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0010_aquivo_matricula_alter_aquivo_arquivo_ponto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquivo',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestaoHR.collaborator', to_field='matricula'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='matricula',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
