# Generated by Django 5.0.7 on 2024-08-10 14:00

import django.db.models.deletion
from django.db import migrations, models


import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0010_aquivo_matricula_alter_aquivo_arquivo_ponto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquivo',
            name='matricula',
            field=models.CharField(blank=True, max_length=15, null=True),  # Mudança de ForeignKey para CharField
        ),
    ]

