# Generated by Django 5.0.7 on 2024-08-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0013_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='desenho_servico',
            field=models.FileField(blank=True, null=True, upload_to='media/desenhoservico/arquivos/'),
        ),
    ]
