# Generated by Django 5.0.7 on 2024-08-12 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0019_demandainterna'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='foto_antes',
            field=models.FileField(blank=True, null=True, upload_to='media/desenhoservico/arquivos/'),
        ),
        migrations.AddField(
            model_name='servico',
            name='foto_depois',
            field=models.FileField(blank=True, null=True, upload_to='media/desenhoservico/arquivos/'),
        ),
        migrations.AlterField(
            model_name='demandainterna',
            name='data_solicitacao',
            field=models.DateField(verbose_name=datetime.datetime(2024, 8, 12, 15, 18, 44, 664042)),
        ),
        migrations.AlterField(
            model_name='servico',
            name='Servico',
            field=models.CharField(choices=[('Plano de Manutenção', 'Plano de Manutenção'), ('Desenho tecnico', 'Desenho tecnico'), ('Ocorrência', 'Ocorrência')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servico',
            name='Status',
            field=models.CharField(choices=[('Em programação', 'Em programação'), ('Em Andamento', 'Em Andamento'), ('Em espera', 'Em espera'), ('Em concluido', 'Em concluido'), ('Em Fechamento', 'Em Fechamento')], max_length=25),
        ),
    ]
