# Generated by Django 5.0.7 on 2024-08-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0023_bancoarquivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancoarquivos',
            name='municipio',
            field=models.CharField(default='Arroio dos ratos', max_length=11),
            preserve_default=False,
        ),
    ]
