# Generated by Django 5.0.7 on 2024-08-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0026_alter_bancoarquivos_ei_oc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancoarquivos',
            name='tipo',
            field=models.CharField(choices=[('Plano de Manutenção', 'Plano de Manutenção'), ('Desenho tecnico', 'Desenho tecnico'), ('Ocorrência', 'Ocorrência')], default='Plano de Manutenção', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bancoarquivos',
            name='municipio',
            field=models.CharField(max_length=50),
        ),
    ]
