# Generated by Django 5.0.7 on 2024-08-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0030_servico_ano_servico_servico_mês_servico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='Status',
            field=models.CharField(choices=[('Programação', 'Programação'), ('Andamento', 'Andamento'), ('Espera', 'Espera'), ('Concluido', 'Concluido'), ('Fechamento', 'Fechamento'), ('Pagamento', 'Pagamento'), ('Recebido', 'Recebido')], max_length=25),
        ),
    ]
