# Generated by Django 5.0.7 on 2024-08-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0031_alter_servico_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bancoarquivos',
            name='Arquivo_complementar',
        ),
    ]
