# Generated by Django 5.0.7 on 2024-08-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0033_alter_demandainterna_data_conclusão_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandainterna',
            name='Observacao',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='demandainterna',
            name='status',
            field=models.CharField(choices=[('Aguardando', 'Aguardando'), ('Andamento', 'Andamento'), ('Realizado', 'Realizado'), ('Correção', 'Correção'), ('Enviado Equatorial', 'Enviado Equatorial'), ('Aprovado Equatorial', 'Aprovado Equatorial'), ('Correção Equatorial', 'Correção Equatorial')], max_length=30),
        ),
        migrations.AlterField(
            model_name='servico',
            name='PEP',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
