# Generated by Django 5.0.7 on 2024-08-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0034_demandainterna_observacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='Servico',
            field=models.CharField(choices=[('Administrativo', 'Administrativo'), ('Operacional', 'Operacional')], max_length=20),
        ),
        migrations.AlterField(
            model_name='demandainterna',
            name='data_solicitacao',
            field=models.DateField(default='2024-05-20'),
            preserve_default=False,
        ),
    ]
