# Generated by Django 5.0.7 on 2024-09-04 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0038_alter_demandainterna_data_conclusão'),
    ]

    operations = [
        migrations.CreateModel(
            name='arquivos_foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='FotosCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poste_antes', models.ImageField(blank=True, null=True, upload_to='media/fotos/campos')),
                ('Poste_depois', models.ImageField(blank=True, null=True, upload_to='media/fotos/campos')),
                ('cava_antes', models.ImageField(blank=True, null=True, upload_to='media/fotos/campos')),
                ('cava_depois', models.ImageField(blank=True, null=True, upload_to='media/fotos/campos')),
                ('GPS_antes', models.ImageField(blank=True, null=True, upload_to='media/fotos/campos')),
                ('GPS_depois', models.ImageField(blank=True, null=True, upload_to='media/fotos/campos')),
                ('Estrutura_antes', models.ImageField(blank=True, null=True, upload_to='media/fotos/campos')),
                ('Estrutura_depois', models.ImageField(blank=True, null=True, upload_to='media/fotos/campos')),
                ('panoramica', models.ImageField(blank=True, null=True, upload_to='media/fotos/campos')),
                ('Equipamento_antes', models.ImageField(blank=True, null=True, upload_to='media/fotos/campos')),
                ('Equipamento_depois', models.ImageField(blank=True, null=True, upload_to='media/fotos/campos')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='GestaoHR.arquivos_foto')),
            ],
        ),
    ]
