# Generated by Django 5.0.7 on 2024-09-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0040_sesmt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesmt',
            name='Ultima_atualização',
            field=models.CharField(default='13/01/2024', max_length=50),
            preserve_default=False,
        ),
    ]
