# Generated by Django 5.0.7 on 2024-09-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0041_sesmt_ultima_atualização'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sesmt',
            old_name='Brigada_emergencia',
            new_name='Brigada_emergerncia',
        ),
    ]
