# Generated by Django 5.0.7 on 2024-09-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0043_arquivosesmt'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoscampo',
            name='poste',
            field=models.CharField(default='1', max_length=4),
            preserve_default=False,
        ),
    ]
