# Generated by Django 5.0.7 on 2024-09-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0048_produto_movimentacaoestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='realizado_para',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
