# Generated by Django 5.0.7 on 2024-09-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0049_movimentacaoestoque_realizado_para'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoscampo',
            name='poste',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='fotoscampo',
            name='projeto',
            field=models.CharField(max_length=15),
        ),
    ]
