# Generated by Django 5.0.7 on 2024-10-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0056_alter_demandainterna_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadernoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='media/cadernos/servicos/')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
