# Generated by Django 5.0.7 on 2024-11-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0063_programacaoequipes_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iten', models.CharField(max_length=3)),
                ('codigo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('QTD', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='programacaoequipes',
            name='turno',
            field=models.CharField(choices=[('Dia', 'Dia'), ('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Diversos', 'Diversos')], max_length=8),
        ),
        migrations.AlterField(
            model_name='servico',
            name='Status',
            field=models.CharField(choices=[('Programação', 'Programação'), ('Andamento', 'Andamento'), ('Espera', 'Espera'), ('Concluido', 'Concluido'), ('Fechamento', 'Fechamento'), ('Almoxerifado', 'Almoxerifado'), ('Pagamento', 'Pagamento'), ('Recebido', 'Recebido')], default='', max_length=25),
        ),
    ]
