# Generated by Django 5.0.7 on 2024-11-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0065_fotoscampo_cidade_fotoscampo_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoscampo',
            name='GPS',
            field=models.CharField(default='inserir', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fotoscampo',
            name='Supervisor',
            field=models.CharField(default='Josivan', max_length=25),
            preserve_default=False,
        ),
    ]
