# Generated by Django 5.0.7 on 2024-11-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0066_fotoscampo_gps_fotoscampo_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoscampo',
            name='Tela_Ocorencia',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/campos'),
        ),
        migrations.AddField(
            model_name='fotoscampo',
            name='Trajeto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/campos'),
        ),
    ]
