# Generated by Django 5.0.7 on 2025-01-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GestaoHR", "0072_alter_collaborator_matricula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aquivo",
            name="Nome",
            field=models.CharField(max_length=6),
        ),
    ]
