# Generated by Django 5.0.7 on 2025-01-05 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GestaoHR", "0077_delete_aquivo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FotosCampo",
        ),
    ]
