# Generated by Django 5.0.7 on 2025-01-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GestaoHR", "0078_delete_fotoscampo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ArquivoSesmt",
        ),
        migrations.DeleteModel(
            name="Document",
        ),
        migrations.DeleteModel(
            name="SESMT",
        ),
    ]
