# Generated by Django 5.0.7 on 2025-01-06 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GestaoHR", "0079_delete_arquivosesmt_delete_document_delete_sesmt"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MovimentacaoEstoque",
        ),
        migrations.DeleteModel(
            name="Produto",
        ),
    ]
