# Generated by Django 5.0.7 on 2025-01-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GestaoHR", "0080_delete_movimentacaoestoque_delete_produto"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProgramacaoEquipes",
        ),
    ]
