# Generated by Django 5.0.7 on 2025-01-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GestaoHR", "0081_delete_programacaoequipes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BancoArquivos",
        ),
    ]
