# Generated by Django 5.0.7 on 2025-01-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GestaoHR", "0088_alter_collaborator_matricula"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collaborator",
            name="matricula",
        ),
    ]
