# Generated by Django 5.0.7 on 2025-01-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GestaoHR", "0090_collaborator_matricula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collaborator",
            name="matricula",
            field=models.CharField(default="123", max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
