# Generated by Django 5.0.7 on 2025-01-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GestaoHR", "0091_alter_collaborator_matricula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collaborator",
            name="matricula",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
