# Generated by Django 5.0.7 on 2025-01-07 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Arquivo", "0002_aquivo_matricula"),
        ("GestaoHR", "0090_collaborator_matricula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aquivo",
            name="matricula",
            field=models.ForeignKey(
                default="323232",
                on_delete=django.db.models.deletion.CASCADE,
                to="GestaoHR.collaborator",
            ),
            preserve_default=False,
        ),
    ]
