# Generated by Django 5.0.7 on 2025-01-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Arquivo", "0003_alter_aquivo_matricula"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aquivo",
            name="matricula",
        ),
    ]
