services:
  web:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python manage.py runserver 0.0.0.0:8001
    env_file:
    - .env.dev
