# Generated by Django 5.0.7 on 2025-01-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DemandaInterna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Atividade", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Desenho", "Desenho"),
                            ("Medição", "Medição"),
                            ("Verificar campo", "Verificar Campo"),
                            ("Documentação", "Documentação"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "responsavel",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Aguardando", "Aguardando"),
                            ("Andamento", "Andamento"),
                            ("Realizado", "Realizado"),
                            ("Correção", "Correção"),
                            ("OPEX", "OPEX"),
                            ("Aguardando Equatorial", "Aguardando Equatorial"),
                            ("Enviado Equatorial", "Enviado Equatorial"),
                            ("Aprovado Equatorial", "Aprovado Equatorial"),
                            ("Correção Equatorial", "Correção Equatorial"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "responsavel_demanda",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                ("Observacao", models.TextField(blank=True, max_length=200, null=True)),
                (
                    "arquivos",
                    models.FileField(
                        blank=True, null=True, upload_to="media/desenhoservico/Interna/"
                    ),
                ),
                (
                    "arquivos_complementar",
                    models.FileField(
                        blank=True, null=True, upload_to="media/desenhoservico/Interna/"
                    ),
                ),
                (
                    "arquivos_complementar1",
                    models.FileField(
                        blank=True, null=True, upload_to="media/desenhoservico/Interna/"
                    ),
                ),
                (
                    "arquivos_complementar2",
                    models.FileField(
                        blank=True, null=True, upload_to="media/desenhoservico/Interna/"
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("acesso_demandaInterna2", "Acesso ao gestao de demandainterna2")
                ],
            },
        ),
    ]
