# Generated by Django 5.0.7 on 2025-01-05 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Equipe", "0002_alter_equipe_codigo_equipe"),
    ]

    operations = [
        migrations.CreateModel(
            name="arquivos_foto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projeto", models.CharField(max_length=25)),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="FotosCampo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projeto", models.CharField(max_length=15)),
                ("poste", models.CharField(max_length=4)),
                (
                    "Poste_antes",
                    models.ImageField(blank=True, null=True, upload_to="fotos/campos"),
                ),
                (
                    "Poste_depois",
                    models.ImageField(blank=True, null=True, upload_to="fotos/campos"),
                ),
                (
                    "cava_antes",
                    models.ImageField(blank=True, null=True, upload_to="fotos/campos"),
                ),
                (
                    "cava_depois",
                    models.ImageField(blank=True, null=True, upload_to="fotos/campos"),
                ),
                (
                    "GPS_antes",
                    models.ImageField(blank=True, null=True, upload_to="fotos/campos"),
                ),
                (
                    "GPS_depois",
                    models.ImageField(blank=True, null=True, upload_to="fotos/campos"),
                ),
                (
                    "Estrutura_antes",
                    models.ImageField(blank=True, null=True, upload_to="fotos/campos"),
                ),
                (
                    "Estrutura_depois",
                    models.ImageField(blank=True, null=True, upload_to="fotos/campos"),
                ),
                (
                    "panoramica",
                    models.ImageField(blank=True, null=True, upload_to="fotos/campos"),
                ),
                (
                    "Equipamento_antes",
                    models.ImageField(blank=True, null=True, upload_to="fotos/campos"),
                ),
                (
                    "Equipamento_depois",
                    models.ImageField(blank=True, null=True, upload_to="fotos/campos"),
                ),
                (
                    "Numero_serie_antes",
                    models.ImageField(blank=True, null=True, upload_to="fotos/campos"),
                ),
                (
                    "Numero_serie_depois",
                    models.ImageField(blank=True, null=True, upload_to="fotos/campos"),
                ),
                (
                    "Numero_sap_antes",
                    models.ImageField(blank=True, null=True, upload_to="fotos/campos"),
                ),
                (
                    "Numero_sap_depois",
                    models.ImageField(blank=True, null=True, upload_to="fotos/campos"),
                ),
                (
                    "Numero_placa_antes",
                    models.ImageField(blank=True, null=True, upload_to="fotos/campos"),
                ),
                (
                    "Numero_placa_depois",
                    models.ImageField(blank=True, null=True, upload_to="fotos/campos"),
                ),
                (
                    "Poda_antes",
                    models.ImageField(blank=True, null=True, upload_to="fotos/campos"),
                ),
                (
                    "Poda_depois",
                    models.ImageField(blank=True, null=True, upload_to="fotos/campos"),
                ),
                (
                    "concreto_calcada_antes",
                    models.ImageField(blank=True, null=True, upload_to="fotos/campos"),
                ),
                (
                    "concreto_calcada_depois",
                    models.ImageField(blank=True, null=True, upload_to="fotos/campos"),
                ),
                (
                    "Tela_Ocorencia",
                    models.ImageField(blank=True, null=True, upload_to="fotos/campos"),
                ),
                (
                    "Trajeto",
                    models.ImageField(blank=True, null=True, upload_to="fotos/campos"),
                ),
                ("Data", models.DateField(blank=True, null=True)),
                ("Supervisor", models.CharField(max_length=25)),
                (
                    "Cidade",
                    models.CharField(
                        choices=[
                            ("ALVORADA", "ALVORADA"),
                            ("ARROIO DOS RATOS", "ARROIO DOS RATOS"),
                            ("BARRA DO RIBEIRO", "BARRA DO RIBEIRO"),
                            ("BUTIÁ", "BUTIÁ"),
                            ("CHARQUEADAS", "CHARQUEADAS"),
                            ("ELDORADO DO SUL", "ELDORADO DO SUL"),
                            ("GUAÍBA", "GUAÍBA"),
                            ("MARIANA PIMENTEL", "MARIANA PIMENTEL"),
                            ("MINAS DO LEÃO", "MINAS DO LEÃO"),
                            ("PANTANO GRANDE", "PANTANO GRANDE"),
                            ("PORTO ALEGRE", "PORTO ALEGRE"),
                            ("SÃO JERÔNIMO", "SÃO JERÔNIMO"),
                            ("VIAMÃO", "VIAMÃO"),
                            ("AMARAL FERRADOR", "AMARAL FERRADOR"),
                            ("ARAMBARÉ", "ARAMBARÉ"),
                            ("ARROIO DO PADRE", "ARROIO DO PADRE"),
                            ("ARROIO GRANDE", "ARROIO GRANDE"),
                            ("BAGÉ", "BAGÉ"),
                            ("BARAO DO TRIUNFO", "BARAO DO TRIUNFO"),
                            ("CAMAQUÃ", "CAMAQUÃ"),
                            ("CANDIOTA", "CANDIOTA"),
                            ("CANGUÇU", "CANGUÇU"),
                            ("CAPÃO DO LEÃO", "CAPÃO DO LEÃO"),
                            ("CERRITO", "CERRITO"),
                            ("CERRO GRANDE DO SUL", "CERRO GRANDE DO SUL"),
                            ("CHUÍ", "CHUÍ"),
                            ("CHUVISCA", "CHUVISCA"),
                            ("CRISTAL", "CRISTAL"),
                            ("DOM FELICIANO", "BDOM FELICIANO"),
                            ("DOM PEDRITO", "DOM PEDRITO"),
                            ("ENCRUZILHADA DO SUL", "ENCRUZILHADA DO SUL"),
                            ("HERVAL", "HERVAL"),
                            ("HULHA NEGRA", "HULHA NEGRA"),
                            ("JAGUARÃO", "JAGUARÃO"),
                            ("LAVRAS DO SUL", "LAVRAS DO SUL"),
                            ("MORRO REDONDO", "MORRO REDONDO"),
                            ("PEDRAS ALTAS", "PEDRAS ALTAS"),
                            ("PEDRO OSÓRIO", "PEDRO OSÓRIO"),
                            ("PELOTAS", "PELOTAS"),
                            ("JAGUARÃO", "JAGUARÃO"),
                            ("PINHEIRO MACHADO", "PINHEIRO MACHADO"),
                            ("PIRATINI", "PIRATINI"),
                            ("RIO GRANDE", "RIO GRANDE"),
                            ("SÃO LOURENÇO DO SUL", "SÃO LOURENÇO DO SUL"),
                            ("SENTINELA DO SUL", "SENTINELA DO SUL"),
                            ("Sertão Santana", "Sertão Santana"),
                            ("SANTA VITÓRIA DO PALMAR", "SANTA VITÓRIA DO PALMAR"),
                            ("TAPES", "TAPES"),
                        ],
                        max_length=100,
                    ),
                ),
                ("Endereco", models.CharField(max_length=300)),
                ("ocorrencia", models.CharField(max_length=20)),
                ("GPS", models.CharField(max_length=20)),
                ("servico", models.CharField(max_length=300)),
                ("horario_inicio", models.TimeField()),
                ("horario_fim", models.TimeField(blank=True, null=True)),
                (
                    "Equipe",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="Equipe.equipe",
                    ),
                ),
            ],
            options={
                "permissions": [("acesso_fotoscampo", "Acesso as fotos de campo")],
            },
        ),
    ]
