# Generated by Django 5.0.7 on 2025-01-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Equipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipe",
            name="Codigo_Equipe",
            field=models.CharField(max_length=50),
        ),
    ]
