# Generated by Django 5.0.7 on 2025-01-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aquivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nome", models.CharField(max_length=100)),
                (
                    "Arquivo_ponto",
                    models.FileField(upload_to="media/imagens/Controle_folha_ponto/"),
                ),
                (
                    "Mes",
                    models.CharField(
                        choices=[
                            ("Jan", "Jan"),
                            ("Fev", "Fev"),
                            ("Mar", "Mar"),
                            ("Abr", "Abr"),
                            ("Mai", "Mai"),
                            ("Jun", "Jun"),
                            ("Jul", "Jul"),
                            ("Ago", "Ago"),
                            ("Set", "Set"),
                            ("Out", "Out"),
                            ("Nov", "Nov"),
                            ("Dez", "Dez"),
                        ],
                        max_length=6,
                    ),
                ),
                ("Ano", models.IntegerField(default=2025)),
            ],
        ),
    ]
