# Generated by Django 5.0.7 on 2025-01-07 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Arquivo", "0004_remove_aquivo_matricula"),
        ("GestaoHR", "0092_alter_collaborator_matricula"),
    ]

    operations = [
        migrations.AddField(
            model_name="aquivo",
            name="idade",
            field=models.CharField(default="1", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aquivo",
            name="matriculas",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="GestaoHR.collaborator",
            ),
            preserve_default=False,
        ),
    ]
