# Generated by Django 5.0.7 on 2025-01-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Codigo_Equipe", models.CharField(max_length=50, unique=True)),
                ("Nome_encarregado", models.CharField(max_length=150)),
                (
                    "Mebro_equipe1",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "Mebro_equipe2",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "Mebro_equipe3",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "Mebro_equipe4",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "Mebro_equipe5",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "Mebro_equipe6",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
            ],
        ),
    ]
