# Generated by Django 5.0.7 on 2024-08-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='Data_contratacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
