# Generated by Django 5.0.7 on 2024-08-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0007_aquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aquivo',
            name='data_upload',
        ),
    ]
