# Generated by Django 5.0.7 on 2024-08-10 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0009_aquivo_ano_aquivo_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquivo',
            name='matricula',
            field=models.ForeignKey(default='19', on_delete=django.db.models.deletion.CASCADE, to='GestaoHR.collaborator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aquivo',
            name='Arquivo_ponto',
            field=models.FileField(upload_to='media/imagens/Controle_folha_ponto/'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='ASO',
            field=models.FileField(blank=True, null=True, upload_to='media/ASO/'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='Controle_folha_ponto',
            field=models.FileField(blank=True, null=True, upload_to='media/Controle_folha_ponto/'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='Seguro_de_vida',
            field=models.FileField(blank=True, null=True, upload_to='media/Seguro_vida/'),
        ),
    ]
