# Generated by Django 5.0.7 on 2024-08-11 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0011_alter_aquivo_matricula_alter_collaborator_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aquivo',
            name='matricula',
        ),
    ]
