# Generated by Django 5.0.7 on 2024-08-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0012_remove_aquivo_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_Servico', models.CharField(max_length=100)),
                ('EI', models.IntegerField()),
                ('Servico', models.CharField(choices=[('Execução de serviço', 'Execução de serviço'), ('Desenho tecnico', 'Desenho tecnico'), ('Ocorrência', 'Ocorrência')], max_length=50)),
                ('data_da_solicitacao', models.DateField()),
                ('Municipio', models.CharField(max_length=50)),
                ('Endereco', models.CharField(max_length=100)),
                ('data_programacao', models.DateField(blank=True, null=True)),
                ('Observacao', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
