# Generated by Django 5.0.7 on 2024-08-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0014_servico_desenho_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='Status',
            field=models.CharField(choices=[('Em programação', 'Em programação'), ('Em Andamento', 'Em Andamento'), ('Em espera', 'Em espera'), ('Em concluido', 'Em concluido')], default='Em andamento', max_length=25),
            preserve_default=False,
        ),
    ]
