# Generated by Django 5.0.7 on 2024-08-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0015_servico_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='EI',
            new_name='PEP',
        ),
    ]
