# Generated by Django 5.0.7 on 2024-08-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0017_servico_valor_final_servico_valor_parcial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='Numero_Servico',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='PEP',
            field=models.IntegerField(unique=True),
        ),
    ]
