# Generated by Django 5.0.7 on 2024-08-12 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0018_alter_servico_numero_servico_alter_servico_pep'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandaInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Atividade', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Desenho', 'Desenho'), ('Medição', 'Medição'), ('Verificar campo', 'Verificar Campo'), ('Documentação', 'Documentação')], max_length=50)),
                ('status', models.CharField(choices=[('Aguardando', 'Aguardando'), ('Andamento', 'Andamento'), ('Realizando', 'Realizado'), ('Correção', 'Correção')], max_length=30)),
                ('data_solicitacao', models.DateField(verbose_name=datetime.datetime(2024, 8, 12, 11, 38, 23, 865094))),
                ('data_conclusão', models.DateField(blank=True, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
