# Generated by Django 5.0.7 on 2024-08-13 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0020_servico_foto_antes_servico_foto_depois_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandainterna',
            name='arquivos',
            field=models.FileField(blank=True, null=True, upload_to='media/desenhoservico/Interna/'),
        ),
        migrations.AddField(
            model_name='demandainterna',
            name='arquivos_complementar',
            field=models.FileField(blank=True, null=True, upload_to='media/desenhoservico/Interna/'),
        ),
        migrations.AddField(
            model_name='demandainterna',
            name='arquivos_complementar1',
            field=models.FileField(blank=True, null=True, upload_to='media/desenhoservico/Interna/'),
        ),
        migrations.AddField(
            model_name='demandainterna',
            name='arquivos_complementar2',
            field=models.FileField(blank=True, null=True, upload_to='media/desenhoservico/Interna/'),
        ),
        migrations.AlterField(
            model_name='demandainterna',
            name='data_solicitacao',
            field=models.DateField(verbose_name=datetime.datetime(2024, 8, 13, 8, 49, 51, 436296)),
        ),
    ]
