# Generated by Django 5.0.7 on 2024-08-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0021_demandainterna_arquivos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandainterna',
            name='data_solicitacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
