# Generated by Django 5.0.7 on 2024-08-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0022_alter_demandainterna_data_solicitacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancoArquivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EI_OC', models.CharField(max_length=100)),
                ('Responsavel', models.CharField(max_length=50)),
                ('AS_Biult', models.FileField(upload_to='media/desenhoservico/Arquivos/')),
                ('DWG', models.FileField(blank=True, null=True, upload_to='media/desenhoservico/Arquivos/')),
                ('AES', models.FileField(blank=True, null=True, upload_to='media/desenhoservico/Arquivos/')),
                ('ACOS', models.FileField(blank=True, null=True, upload_to='media/desenhoservico/Arquivos/')),
                ('Arquivo_complementar', models.FileField(blank=True, null=True, upload_to='media/desenhoservico/Arquivos/')),
            ],
        ),
    ]
