# Generated by Django 5.0.7 on 2024-08-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0024_bancoarquivos_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancoarquivos',
            name='Medicao',
            field=models.FileField(blank=True, null=True, upload_to='media/desenhoservico/Arquivos/'),
        ),
    ]
