# Generated by Django 5.0.7 on 2024-08-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0027_bancoarquivos_tipo_alter_bancoarquivos_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancoarquivos',
            name='municipio',
            field=models.CharField(choices=[('ALVORADA', 'ALVORADA'), ('ARROIO DOS RATOS', 'ARROIO DOS RATOS'), ('BARRA DO RIBEIRO', 'BARRA DO RIBEIRO'), ('BUTIÁ', 'BUTIÁ'), ('CHARQUEADAS', 'CHARQUEADAS'), ('ELDORADO DO SUL', 'ELDORADO DO SUL'), ('GUAÍBA', 'GUAÍBA'), ('MARIANA PIMENTEL', 'MARIANA PIMENTEL'), ('MINAS DO LEÃO', 'MINAS DO LEÃO'), ('PANTANO GRANDE', 'PANTANO GRANDE'), ('PORTO ALEGRE', 'PORTO ALEGRE'), ('SÃO JERÔNIMO', 'SÃO JERÔNIMO'), ('VIAMÃO', 'VIAMÃO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servico',
            name='Municipio',
            field=models.CharField(choices=[('ALVORADA', 'ALVORADA'), ('ARROIO DOS RATOS', 'ARROIO DOS RATOS'), ('BARRA DO RIBEIRO', 'BARRA DO RIBEIRO'), ('BUTIÁ', 'BUTIÁ'), ('CHARQUEADAS', 'CHARQUEADAS'), ('ELDORADO DO SUL', 'ELDORADO DO SUL'), ('GUAÍBA', 'GUAÍBA'), ('MARIANA PIMENTEL', 'MARIANA PIMENTEL'), ('MINAS DO LEÃO', 'MINAS DO LEÃO'), ('PANTANO GRANDE', 'PANTANO GRANDE'), ('PORTO ALEGRE', 'PORTO ALEGRE'), ('SÃO JERÔNIMO', 'SÃO JERÔNIMO'), ('VIAMÃO', 'VIAMÃO')], max_length=50),
        ),
    ]
