# Generated by Django 5.0.7 on 2024-08-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0036_alter_demandainterna_data_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandainterna',
            name='responsavel_demanda',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
