# Generated by Django 5.0.7 on 2024-08-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0037_demandainterna_responsavel_demanda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandainterna',
            name='data_conclusão',
            field=models.DateField(blank=True, null=True),
        ),
    ]
