# Generated by Django 5.0.7 on 2024-09-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0039_arquivos_foto_fotoscampo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SESMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brigada_emergencia', models.FileField(blank=True, null=True, upload_to='media/sesmt/brigada')),
                ('CIPA', models.FileField(blank=True, null=True, upload_to='media/sesmt/cipa')),
                ('CNPJ_CRB', models.FileField(blank=True, null=True, upload_to='media/sesmt/cnpj')),
                ('CRB', models.FileField(blank=True, null=True, upload_to='media/sesmt/crb')),
                ('Documentacao_veiculo', models.FileField(blank=True, null=True, upload_to='media/sesmt/documentoveiculo')),
                ('manual_veiculo', models.FileField(blank=True, null=True, upload_to='media/sesmt/manual')),
                ('orcamentos', models.FileField(blank=True, null=True, upload_to='media/sesmt/orcamento')),
                ('PCSMO', models.FileField(blank=True, null=True, upload_to='media/sesmt/pcsmo')),
                ('prg', models.FileField(blank=True, null=True, upload_to='media/sesmt/prg')),
                ('plano_de_atendimento_emergencia', models.FileField(blank=True, null=True, upload_to='media/sesmt/planodeatendimento')),
                ('plano_de_manutencao_frota', models.FileField(blank=True, null=True, upload_to='media/sesmt/plfrota')),
                ('POP_lM_construcao', models.FileField(blank=True, null=True, upload_to='media/sesmt/POPLMCONST')),
                ('POP_LV_contrucao', models.FileField(blank=True, null=True, upload_to='media/sesmt/POPLVCONST')),
                ('POP_sesmt', models.FileField(blank=True, null=True, upload_to='media/sesmt/POPSESMT')),
                ('PPCI', models.FileField(blank=True, null=True, upload_to='media/sesmt/PPCI')),
                ('SESMT_t', models.FileField(blank=True, null=True, upload_to='media/sesmt/sesmt_t')),
            ],
        ),
    ]
