# Generated by Django 5.0.7 on 2024-09-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0044_fotoscampo_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivos_foto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
