# Generated by Django 5.0.7 on 2024-09-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0045_arquivos_foto_ativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborator',
            options={'permissions': [('Acesso_RH', 'Acesso_HR')]},
        ),
    ]
