# Generated by Django 5.0.7 on 2024-10-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0050_alter_fotoscampo_poste_alter_fotoscampo_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoscampo',
            name='Equipamento_antes',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/campos'),
        ),
        migrations.AlterField(
            model_name='fotoscampo',
            name='Equipamento_depois',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/campos'),
        ),
        migrations.AlterField(
            model_name='fotoscampo',
            name='Estrutura_antes',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/campos'),
        ),
        migrations.AlterField(
            model_name='fotoscampo',
            name='Estrutura_depois',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/campos'),
        ),
        migrations.AlterField(
            model_name='fotoscampo',
            name='GPS_antes',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/campos'),
        ),
        migrations.AlterField(
            model_name='fotoscampo',
            name='GPS_depois',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/campos'),
        ),
        migrations.AlterField(
            model_name='fotoscampo',
            name='Poste_antes',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/campos'),
        ),
        migrations.AlterField(
            model_name='fotoscampo',
            name='Poste_depois',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/campos'),
        ),
        migrations.AlterField(
            model_name='fotoscampo',
            name='cava_antes',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/campos'),
        ),
        migrations.AlterField(
            model_name='fotoscampo',
            name='cava_depois',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/campos'),
        ),
        migrations.AlterField(
            model_name='fotoscampo',
            name='panoramica',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/campos'),
        ),
        migrations.AlterField(
            model_name='fotoscampo',
            name='poste',
            field=models.CharField(default='dois', max_length=4),
            preserve_default=False,
        ),
    ]
