# Generated by Django 5.0.7 on 2024-10-16 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0052_alter_collaborator_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bancoarquivos',
            options={'permissions': [('acesso_demandaInterna', 'Acesso ao gestao de demandainterna')]},
        ),
        migrations.AlterModelOptions(
            name='fotoscampo',
            options={'permissions': [('acesso_fotoscampo', 'Acesso as fotos de campo')]},
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'permissions': [('acesso_servicos', 'Acesso ao gestao de servicos')]},
        ),
    ]
