# Generated by Django 5.0.7 on 2024-10-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0053_alter_bancoarquivos_options_alter_fotoscampo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacaoestoque',
            options={'permissions': [('acesso_gestaoestoque', 'Acesso as gestão de estoque')]},
        ),
        migrations.AddField(
            model_name='fotoscampo',
            name='Numero_placa_antes',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/campos'),
        ),
        migrations.AddField(
            model_name='fotoscampo',
            name='Numero_placa_depois',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/campos'),
        ),
        migrations.AddField(
            model_name='fotoscampo',
            name='Numero_serie_antes',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/campos'),
        ),
        migrations.AddField(
            model_name='fotoscampo',
            name='Numero_serie_depois',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/campos'),
        ),
        migrations.AddField(
            model_name='fotoscampo',
            name='Poda_antes',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/campos'),
        ),
        migrations.AddField(
            model_name='fotoscampo',
            name='Poda_depois',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/campos'),
        ),
        migrations.AddField(
            model_name='fotoscampo',
            name='concreto_calcada_antes',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/campos'),
        ),
        migrations.AddField(
            model_name='fotoscampo',
            name='concreto_calcada_depois',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/campos'),
        ),
    ]
