# Generated by Django 5.0.7 on 2024-10-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0054_alter_movimentacaoestoque_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoscampo',
            name='Numero_sap_antes',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/campos'),
        ),
        migrations.AddField(
            model_name='fotoscampo',
            name='Numero_sap_depois',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/campos'),
        ),
    ]
