# Generated by Django 5.0.7 on 2024-10-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0055_fotoscampo_numero_sap_antes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandainterna',
            options={'permissions': [('acesso_demandaInterna2', 'Acesso ao gestao de demandainterna2')]},
        ),
    ]
