# Generated by Django 5.0.7 on 2024-10-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0057_cadernoservico'),
    ]

    operations = [
        migrations.CreateModel(
            name='AES_ACOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aes', models.FileField(blank=True, null=True, upload_to='media/aes')),
                ('acos', models.FileField(blank=True, null=True, upload_to='media/acos')),
            ],
        ),
    ]
