# Generated by Django 5.0.7 on 2024-10-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoHR', '0059_alter_servico_observacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caderno_servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='media/cadernoservico/')),
            ],
        ),
        migrations.DeleteModel(
            name='CadernoServico',
        ),
    ]
