# Generated by Django 5.0.7 on 2025-01-04 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Equipe", "0001_initial"),
        ("GestaoHR", "0067_fotoscampo_tela_ocorencia_fotoscampo_trajeto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotoscampo",
            name="Equipe",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="Equipe.equipe",
            ),
        ),
        migrations.AlterField(
            model_name="aquivo",
            name="Ano",
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name="demandainterna",
            name="status",
            field=models.CharField(
                choices=[
                    ("Aguardando", "Aguardando"),
                    ("Andamento", "Andamento"),
                    ("Realizado", "Realizado"),
                    ("Correção", "Correção"),
                    ("OPEX", "OPEX"),
                    ("Aguardando Equatorial", "Aguardando Equatorial"),
                    ("Enviado Equatorial", "Enviado Equatorial"),
                    ("Aprovado Equatorial", "Aprovado Equatorial"),
                    ("Correção Equatorial", "Correção Equatorial"),
                ],
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="Servico",
        ),
        migrations.DeleteModel(
            name="Equipe",
        ),
    ]
