# Generated by Django 5.0.7 on 2025-01-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GestaoHR", "0068_alter_fotoscampo_equipe_alter_aquivo_ano_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bancoarquivos",
            name="EI_OC",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="collaborator",
            name="CPF",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="collaborator",
            name="RG",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="collaborator",
            name="matricula",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="codigo",
            field=models.CharField(max_length=100),
        ),
    ]
