# Generated by Django 5.0.7 on 2025-01-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GestaoHR", "0070_alter_document_unique_together_alter_document_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="arquivosesmt",
            name="versao_anterior",
        ),
    ]
