# Generated by Django 5.0.7 on 2025-01-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GestaoHR", "0071_remove_arquivosesmt_versao_anterior"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collaborator",
            name="matricula",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
