# Generated by Django 5.0.7 on 2025-01-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GestaoHR", "0073_alter_aquivo_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aquivo",
            name="Nome",
            field=models.CharField(max_length=100),
        ),
    ]
