# Generated by Django 5.0.7 on 2025-01-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GestaoHR", "0075_alter_collaborator_cpf"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DemandaInterna",
        ),
        migrations.AlterUniqueTogether(
            name="document",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="document",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
