# Generated by Django 5.0.7 on 2025-01-04 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "GestaoHR",
            "0076_delete_demandainterna_alter_document_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Aquivo",
        ),
    ]
