# Generated by Django 5.0.7 on 2025-01-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GestaoHR", "0082_delete_bancoarquivos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collaborator",
            name="matricula",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
