# Generated by Django 5.0.7 on 2025-01-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GestaoHR", "0086_alter_collaborator_matricula"),
    ]

    operations = []
