# Generated by Django 5.0.7 on 2025-01-07 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Equipe", "0002_alter_equipe_codigo_equipe"),
        ("GestaoHR", "0089_remove_collaborator_matricula"),
    ]

    operations = [
        migrations.AddField(
            model_name="collaborator",
            name="matricula",
            field=models.ForeignKey(
                blank=True,
                max_length=15,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Equipe.equipe",
                unique=True,
            ),
        ),
    ]
