# Generated by Django 5.0.7 on 2025-01-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArquivoSesmt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nome", models.CharField(max_length=50)),
                ("arquivo", models.FileField(upload_to="media/sesmt/sesmt_t")),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="documents/")),
                ("version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SESMT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Brigada_emergerncia",
                    models.FileField(
                        blank=True, null=True, upload_to="media/sesmt/brigada"
                    ),
                ),
                (
                    "CIPA",
                    models.FileField(
                        blank=True, null=True, upload_to="media/sesmt/cipa"
                    ),
                ),
                (
                    "CNPJ_CRB",
                    models.FileField(
                        blank=True, null=True, upload_to="media/sesmt/cnpj"
                    ),
                ),
                (
                    "CRB",
                    models.FileField(
                        blank=True, null=True, upload_to="media/sesmt/crb"
                    ),
                ),
                (
                    "Documentacao_veiculo",
                    models.FileField(
                        blank=True, null=True, upload_to="media/sesmt/documentoveiculo"
                    ),
                ),
                (
                    "manual_veiculo",
                    models.FileField(
                        blank=True, null=True, upload_to="media/sesmt/manual"
                    ),
                ),
                (
                    "orcamentos",
                    models.FileField(
                        blank=True, null=True, upload_to="media/sesmt/orcamento"
                    ),
                ),
                (
                    "PCSMO",
                    models.FileField(
                        blank=True, null=True, upload_to="media/sesmt/pcsmo"
                    ),
                ),
                (
                    "prg",
                    models.FileField(
                        blank=True, null=True, upload_to="media/sesmt/prg"
                    ),
                ),
                (
                    "plano_de_atendimento_emergencia",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="media/sesmt/planodeatendimento",
                    ),
                ),
                (
                    "plano_de_manutencao_frota",
                    models.FileField(
                        blank=True, null=True, upload_to="media/sesmt/plfrota"
                    ),
                ),
                (
                    "POP_lM_construcao",
                    models.FileField(
                        blank=True, null=True, upload_to="media/sesmt/POPLMCONST"
                    ),
                ),
                (
                    "POP_LV_contrucao",
                    models.FileField(
                        blank=True, null=True, upload_to="media/sesmt/POPLVCONST"
                    ),
                ),
                (
                    "POP_sesmt",
                    models.FileField(
                        blank=True, null=True, upload_to="media/sesmt/POPSESMT"
                    ),
                ),
                (
                    "PPCI",
                    models.FileField(
                        blank=True, null=True, upload_to="media/sesmt/PPCI"
                    ),
                ),
                (
                    "SESMT_t",
                    models.FileField(
                        blank=True, null=True, upload_to="media/sesmt/sesmt_t"
                    ),
                ),
                ("Ultima_atualização", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                fields=("file", "version"), name="unique_file_version"
            ),
        ),
    ]
